version: '3.8'
services:
  api:
    container_name: "hrm_api_${NODE_ENV}"
    image: "hrm_api_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: ./app
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - ./usr/src/api
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  nesjs-network: